### ISSUE TITLE
Optimise check for whether number field contains an imaginary quadratic field

### ISSUE THREAD

**Issue by BarinderBanwait** [isogeny-primes/isogeny-primes#11]
https://github.com/isogeny-primes/isogeny-primes/blob/bbd25527bea6668c6d0e0fcbecd047d6704659e9/isogeny_primes.py#L401

Choosing auxiliary primes is done differently depending on whether or not K contains an imaginary quadratic field, so a check for this is necessary.

The current implementation computes _all_ quadratic subfields and checks whether any of them is imaginary quadratic. This doesn't feel like the most optimal solution.

Is there a better way?

done is: implement better solution, or justify that we can't do better than current implementation

**Comment by koffie** [comment]
Well, I guess for galois fields of odd degree we could just return False immediately. Before putting to much time into this we should first profile the code and check if this is a bottleneck in practice.

**Comment by BarinderBanwait** [comment]
Latest commit adds a quick check as indicated.
