### ISSUE TITLE
Include epsilon info in output

### ISSUE THREAD

**Issue by koffie** [isogeny-primes/isogeny-primes#14]
>Would it be much work to also for every prime in the superset also give a list of all possible epsilon types that might give rise to an isogeny of that prime degree? I am mostly asking because I think this information will be useful in the work that still needs to be done to bring the superset of possible isogeny primes down to the actual set of isogeny primes.

_Originally posted by @koffie in https://github.com/isogeny-primes/isogeny-primes/issues/3#issuecomment-813377123_

I think this should not be to much work. Indeed `tracking_dict_inv_collapsed` as defined on https://github.com/isogeny-primes/isogeny-primes/blob/bbd25527bea6668c6d0e0fcbecd047d6704659e9/isogeny_primes.py#L545

contains al the info I would like. To be more precise I think the info that I would like to see printed is:
```
{eps:q_lcm.prime_divisors() for eps,q_lcm in tracking_dict_inv_collapsed}
```

Since this seems to be not to much work I am creating a separate issue for it.

**Comment by BarinderBanwait** [comment]
Latest commit has added the desired info, which is viewable with the optional flag `--verbose`:

```
sage isogeny_primes.py 'x^3 - x^2 - 2*x + 1' --aux_prime_count 3 --verbose
```

feel free to add more verbose output here and there/change it to what you want to see

**Comment by koffie** [comment]
Wow this was a fast fix! Thanks!

I think this is good enough for now. As soon as we add other verbose output, maybe we should label the data we are outputting! But for now it gives me something to think about/toy with!

Fixed in https://github.com/isogeny-primes/isogeny-primes/commit/a103d7e15997b91f8950c7d0921dfd33923f18f3
