### ISSUE TITLE
Optimize PreTypeOneTwoPrimes

### ISSUE THREAD

**Issue by koffie** [isogeny-primes/isogeny-primes#15]
> This is a long-shot, and I haven't given this much thought, but I wonder if it might be possible to get a uniform version of PreTypeOneTwoPrimes, at least for some degrees, and for Galois fields? This seems hard because the ABC integers we're computing are arising as norms of elements from K; but even if we're able to get a large upper bound on these integers, that would be of massive theoretical interest because it'd be a second step towards a uniform bound on isogenies (the first being your uniformisation of type 2 primes). In the cubic case, by effective chebotarev we know that as we vary over all cubic fields, we're guaranteed to find a totally split principal prime ideal of norm at most Q (say). Let K be this cubic field from which this prime ideal comes. I then reckon that for any other cubic field, when we compute A(eps, frak_q), it is bound to be less than the A(eps, Q) computed using K; a similar thing should happen for B and C.

_Originally posted by @BarinderBanwait in https://github.com/isogeny-primes/isogeny-primes/issues/3#issuecomment-813489459_

I Think that indeed a good lot of work is possible here. I started a section on overleaf for this calles `Pre Type 1/2 primes` however this is not much in it right now. I think there is a lot of room for improvement in Momose's Lemma 2 and Theorem 1 if we also look what kind of information we can get from the primes that do not split completely in K.

One optimization I at least think I see immediately is to make `get_pre_type_one_two_primes` behave more like this:

```
def get_pre_type_one_two_primes(K, norm_bound=126, loop_curves=False, verbose_output=False):
    """Pre type 1-2 primes are the finitely many primes outside of which
    the isogeny character is necessarily of type 2 (or 3, which is not relevant
    for us)."""

    tracking_dict = {}
    Kgal = K.galois_closure('b')
    G_K = Kgal.galois_group()
    C_Kgal = Kgal.class_group()
    epsilons = get_pre_type_one_two_epsilons(Kgal.degree())

    aux_primes = Kgal.primes_of_bounded_norm(norm_bound)
```

for me it seems that whole reason of looking only at primes that split K, is that we are then guaranteed that:

alpha^eps != beta^(12*h_k)

for any frobenius root.

However this latter condition might be true way more often. And as soon as it is satisfied, we get a meaningful bound for the type eps primes.

Getting something truly uniform might be hard cause of the class number that is showing up. I don't immediately see a way how to get around this.

**Comment by koffie** [comment]
So leaving the uniform thing for what it is. I think using also the information from the  inert primes allows us to bound the pre type  1 2 primes by [7, 13, 29, 41, 43] for our specific cubic field. We should discuss this coming friday, but at least I think this massively reduces the primes we need to considder.

**Comment by BarinderBanwait** [comment]
oooo yes, that's a good observation, if I can paraphrase: just use any auxiliary prime frak_q (not just the completely split ones), and if the resulting A,B or C is zero, just throw it away. 

If the only place Momose needs that frak_q is completely split is to show that alpha^eps != beta^(12*h_k), then indeed this will be a massive help to the algorithm, as you seem to have shown that we end up only with 5 candidates!

> Getting something truly uniform might be hard cause of the class number that is showing up. I don't immediately see a way how to get around this.

That's why in my spiel you quoted at the top I took a principal prime ideal, so actually we can ignore the class number. You had the idea (now implemented) that actually we don't need the class number exponents, we only need the order of frak_q in the class group, so if we insist on principal ones then the class number disappears!

**Comment by koffie** [comment]
> oooo yes, that's a good observation, if I can paraphrase: just use any auxiliary prime frak_q (not just the completely split ones), and if the resulting A,B or C is zero, just throw it away.
> 

Yes, indeed! However since lcm(0,a) = 0 and gcd(0,a) = a we don't actually need a different code path for this. We can just add the 0 to the lcm/gcd framework. The only thing we have to be careful about is that we don't call "prime_divisors" on an integer that equals 0 at the end, so there we need some extra handling.

> That's why in my spiel you quoted at the top I took a principal prime ideal, so actually we can ignore the class number. You had the idea (now implemented) that actually we don't need the class number exponents, we only need the order of frak_q in the class group, so if we insist on principal ones then the class number disappears!

Ah yes, but then the discriminant pops up! Since the bound Q that you mention there depends on the discriminant of the number field! There is no uniform chebotarev sadly enough.

**Comment by BarinderBanwait** [comment]
This old issue has long been resolved.
