### ISSUE TITLE
Improve get_weil_polys

### ISSUE THREAD

**Issue by koffie** [isogeny-primes/isogeny-primes#16]
The code for "get_weil_polys" currently is wrong in characteristics 2 and 3 since EC's in those characteristics cannot always be put into short weierstrass form. Additionally currently the running time is `O(res_field.cardinality()^2)` however using theorem 4.1 form http://archive.numdam.org/article/ASENS_1969_4_2_4_521_0.pdf the running time can be made `O(sqrt(res_field.cardinality()))`.

Also for future reference:

it is better to replace
```
frob_polys = frob_polys.union({frob_poly})
```
by
```
frob_polys.add(frob_poly)
```

https://github.com/isogeny-primes/isogeny-primes/blob/a103d7e15997b91f8950c7d0921dfd33923f18f3/isogeny_primes.py#L54-L66

**Comment by BarinderBanwait** [comment]
This has now been merged.
