### ISSUE TITLE
Get prototype version working for a single cubic field

### ISSUE THREAD

**Issue by BarinderBanwait** [isogeny-primes/isogeny-primes#3]
Compute superset of IsogPrimeDeg for [this cubic number field](https://www.lmfdb.org/NumberField/3.3.49.1)

**Comment by koffie** [comment]
Hi Barinder,

Do you have a good overview of what still has to happen for this?

Thanks,
Maarten

**Comment by BarinderBanwait** [comment]
Yes -- essentially it's the epsilons in the PreTypeOneTwoPrimes part, at the moment they're hardcoded for quadratic fields, so I hope to be able to resolve that by the end of the week.

**Comment by BarinderBanwait** [comment]
@koffie Actually scrap that -- I decided to call in sick on all other projects and knuckle down on this; the latest commit "Hello cubics!" now works for the cubic field mentioned above:

```
sage isogeny_primes.py 'x^3 - x^2 - 2*x + 1' --aux_prime_count 2
```

yields after a few seconds

```
superset = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 61, 67, 71, 73, 79, 83, 97, 109, 113, 127, 137, 139, 157, 163, 181, 199, 223, 277, 281, 293, 307, 433, 449, 601, 701, 1049, 1153, 2689, 7069, 7589]
```

As in the previous implementation, this only checks type 2 primes up to 1000 -- our pari script will deal with type 2 primes properly.

This even works for a degree 4 field:

```
sage isogeny_primes.py 'x^4 - x^3 + x^2 - x + 1' --aux_prime_count 2
```

yields

```
superset = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 89, 97, 101, 103, 131, 149, 151, 157, 163, 179, 181, 191, 211, 229, 241, 251, 271, 281, 311, 331, 401, 421, 431, 443, 461, 491, 521, 541, 601, 631, 641, 661, 751, 761, 821, 971, 991, 1031, 1061, 1171, 1201, 1301, 1531, 3331, 4421, 4481, 8011]
```

I haven't tried increasing the `aux_prime_count`; that's likely to increase the run-time by quite a bit. But at least we have a working prototype now! :love_you_gesture:

**Comment by koffie** [comment]
This is awesome! I saw you also merged my now polished code from cocalc! Nice! p.s. the lists are still quite long, and contain quite large primes. I guess this is also partially due to the small amount of aux_primes used, and that especially  the larger primes will disappear using bigger aux prime counts.

Would it be much work to also for every prime in the superset also give a list of all possible epsilon types that might give rise to an isogeny of that prime degree? I am mostly asking because I think this information will be useful in the work that still needs to be done to bring the superset of possible isogeny primes down to the actual set of isogeny primes.

**Comment by koffie** [comment]
@BarinderBanwait 

> I haven't tried increasing the `aux_prime_count`; that's likely to increase the run-time by quite a bit. But at least we have a working prototype now! 🤟

Actually I think the new gcd/lcm optimizations are really showing their merit, since 

```
sage isogeny_primes.py 'x^3 - x^2 - 2*x + 1' --aux_prime_count 30
```

completed in a reasonable amount of time with:

```
superset = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 61, 67, 71, 73, 83, 97, 127, 163, 181]
```

as a result!

**Comment by koffie** [comment]
Some other outputs:

```
~/isogeny_primes$ sage isogeny_primes.py 'x^3 - 3*x - 1' --aux_prime_count 30
type_1_primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 43, 73, 97]
pre_type_2_primes = [3, 17, 19, 37, 53, 73, 89, 107, 109, 127, 181]
type_2_primes = {2, 3, 67, 5, 163, 7, 11, 43, 13, 139, 17, 19, 23, 283, 31}
superset = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 43, 53, 67, 73, 89, 97, 107, 109, 127, 139, 163, 181, 283]
```

```
~/isogeny_primes$ sage isogeny_primes.py 'x^3 - x^2 - 4*x - 1' --aux_prime_count 30
type_1_primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 43, 61, 73]
pre_type_2_primes = [5, 13, 31, 47, 53, 73, 79, 83, 103, 109, 151, 157, 229]
type_2_primes = {2, 3, 67, 5, 163, 7, 11, 43, 13, 17, 19, 83, 23, 31}
superset = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 43, 47, 53, 61, 67, 73, 79, 83, 103, 109, 151, 157, 163, 229]
```

My gut feeling is that (most of) the larger primes in these lists don't belong there. Most of the larger primes seem to come from the pre_type_2_primes and some from the type_2_primes. I'll try to see if there is still some theoretical improvement possible on these fronts.

**Comment by BarinderBanwait** [comment]
Woah! 30 auxiliary primes!!! the most I ever managed on the previous version was 25 and that took the best part of a day to finish! :joy_cat:

This is a long-shot, and I haven't given this much thought, but I wonder if it might be possible to get a uniform version of PreTypeOneTwoPrimes, at least for some degrees, and for Galois fields? This seems hard because the ABC integers we're computing are arising as norms of elements from K; but even if we're able to get a large upper bound on these integers, that would be of massive theoretical interest because it'd be a second step towards a uniform bound on isogenies (the first being your uniformisation of type 2 primes). In the cubic case, by effective chebotarev we know that as we vary over all cubic fields, we're guaranteed to find a totally split principal prime ideal of norm at most Q (say). Let K be this cubic field from which this prime ideal comes. I then reckon that for any other cubic field, when we compute A(eps, frak_q), it is bound to be less than the A(eps, Q) computed using K; a similar thing should happen for B and C.

**Comment by koffie** [comment]
Ok, with the optimizations mentioned in #15 I think we should be able to get the list for this individual cubic field down to:

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 61, 67, 71, 73,  163]

which looks like it is similar in size to the list you started out with for the quadratic isogeny paper. Which means this might be a good point to start looking at specific primes.

**Comment by BarinderBanwait** [comment]
This old issue has come along leaps and bounds since the last comment, and is encouraging to look back at the journey up to now. Closing this to keep the list of issues current so that we know what still needs doing before going live.
