### ISSUE TITLE
uniform bound doesn't depend on the degree

### ISSUE THREAD

**Issue by koffie** [isogeny-primes/isogeny-primes#96]
Right now the uniform bound returned by the function https://github.com/isogeny-primes/isogeny-primes/blob/b0840a0738296d5347e58edfbc18f16ec9e27229/sage_code/type_two_primes.py#L60 doesn't depend on the degree, additionally we do not respect the 10^9 bound of theorem 1.4 in https://arxiv.org/pdf/1309.3595.pdf when the type is LLS

**Comment by BarinderBanwait** [comment]
This is legacy code which isn't being used anywhere, we could safely remove it (except that I'm about to start coding up the algorithms in the uniform bounds paper)

**Comment by koffie** [comment]
Ok, closing this since #98 resolves this.
